name: CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - "src/**"
      - "sanity/**"
      - "rust-toolchain"
      - "Cargo.toml"
      - ".github/workflows/**"
      - "!**.md"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: rustup default nightly && rustup component add clippy --toolchain nightly
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --verbose --workspace
    - name: Run Clippy
      run: cargo clippy --verbose --workspace
